# Change name if you feel like it
name = 'puresignal-relay'
compatibility_date = "2025-01-04"
main = "worker.js"

# Durable Objects binding
[[durable_objects.bindings]]
name = "RELAY_WEBSOCKET"
class_name = "RelayWebSocket"

# D1 Database binding
# Important! Change name and id settings to your own
[[d1_databases]]
binding = "RELAY_DATABASE"
database_name = "puresignal-relay-db"
database_id = "0859bdfb-644a-4eec-a013-aeab9cefc793"

# R2 bucket binding for event archive
[[r2_buckets]]
binding = "EVENT_ARCHIVE"
bucket_name = "puresignal-relay-storage"

# CPU limits (lower to 10 if not on paid Workers plan)
[limits]
cpu_ms = 30000

# Enable logs (on by default, but can disable)
[observability.logs]
enabled = true

# Durable Object migration with SQLite storage backend
[[migrations]]
tag = "v3"
new_sqlite_classes = ["RelayWebSocket"]

# Add scheduled worker for archiving
[triggers]
crons = ["0 */6 * * *"]  # Run every 6 hours
